language: python

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx
  include:
    #- os: linux
    #  dist: xenial
    #  python: 3.5
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
    - os: linux
      dist: xenial
      python: 3.8-dev
    - os: osx
      language: generic

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      # Install from latest CRAN binary build for OS X
      wget https://cloud.r-project.org/bin/macosx/R-latest.pkg -O /tmp/R-latest.pkg
      echo "Installing OS X binary package for R"
      sudo installer -pkg "/tmp/R-latest.pkg" -target /
      rm "/tmp/R-latest.pkg"
      brew update
      brew upgrade python3
      python3 -m venv py3_env 
      source py3_env/bin/activate
    else
      sudo apt-get install -y lsb-release
      sudo apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      sudo add-apt-repository \
        --yes \
        "deb https://cloud.r-project.org/bin/linux/ubuntu/ $(lsb_release -c -s)-cran36/"
      cat /etc/apt/sources.list
      sudo apt-get update -qq
      sudo apt-get install -y r-base
    fi
  - |
    sudo Rscript ./install_r_packages.r dplyr ggplot2 tidyr
    pip install flake8 pytest codecov pytest-cov
    pip install ipython tzlocal


addons:
  apt:
    update: true

install:
  - RPY_CFFI_MODE=ABI python setup.py install
  - RPY_CFFI_MODE=API python setup.py install
  - RPY_CFFI_MODE=BOTH python setup.py install

# command to run tests
script:
  - export RPY_CFFI_MODE=ABI
  - ./run_linting.sh
  - |
    pytest \
    --cov=rpy2.rinterface_lib \
    --cov=rpy2.rinterface \
    --cov=rpy2.rlike \
    --cov=rpy2.ipython \
    --cov=rpy2.robjects \
    rpy2/tests
  - |
    pytest \
    --cov-append \
    --cov=rpy2.rinterface_lib.embedded \
    rpy2/tests/rinterface/test_noinitialization.py
  - |
    pytest \
    --cov-append \
    --cov=rpy2.rinterface_lib.embedded \
    rpy2/tests/rinterface/test_endr.py
  - pip install numpy
  - |
    pytest \
    --cov-append \
    --cov=rpy2.rinterface_lib \
    --cov=rpy2.rinterface \
    --cov=rpy2.rlike \
    --cov=rpy2.ipython \
    --cov=rpy2.robjects \
    rpy2/tests
  - pip install pandas
  - |
    pytest \
    --cov-append \
    --cov=rpy2.rinterface_lib \
    --cov=rpy2.rinterface \
    --cov=rpy2.rlike \
    --cov=rpy2.ipython \
    --cov=rpy2.robjects \
    rpy2/tests

after_success:
  - codecov
